//! SOURCE A: reads the state of background sessions persisted by the
//! Claude Code supervisor (~/.claude/jobs/<id>/state.json) and watches the
//! directory to react to changes. See docs/DATA-SOURCES.md.
//!
//! Schema verified empirically on 2026-06-06 against real sessions.
//! Actual fields (all camelCase in the JSON):
//!   state:  "working" | "blocked" | "done" | "stopped" | "failed"
//!   tempo:  "active" | "idle" | "blocked"  (orthogonal to state)
//!   detail: progress string (summary/title do NOT exist — those are not real fields)
//!   needs:  user question or "approve <Tool>: <path>" (permission)
//!   intent: original prompt (fallback for detail)
//!   name:   short name generated by the supervisor (optional)
//!   sessionId, daemonShort, cwd, createdAt, updatedAt: camelCase
//!
//! Empirically observed combinations:
//!   state=working + tempo=active               → Working (actively processing)
//!   state=working + tempo=idle                 → Working (waiting for shell task)
//!   state=working + tempo=blocked              → WaitingPermission (needs=approve …)
//!   state=blocked + tempo=blocked              → WaitingInput (needs=<user question>)
//!   state=done    + tempo=idle                 → Completed
//!   state=stopped + tempo=idle                 → Unknown (stopped by user)
//!   state=failed  + tempo=idle                 → Error

use crate::refresh;
use crate::state::{project_from_cwd, Instance, InstanceState, Source, Store};
use crate::transcript;
use notify::{RecommendedWatcher, RecursiveMode, Watcher};
use serde::Deserialize;
use std::path::PathBuf;
use std::sync::mpsc::channel;
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use tauri::AppHandle;

/// Defensive schema (all Option) for ~/.claude/jobs/<id>/state.json.
/// Verified empirically; deserializes with serde(rename_all = "camelCase") to
/// map sessionId, createdAt, updatedAt directly.
#[derive(Deserialize, Default)]
#[serde(rename_all = "camelCase")]
struct JobState {
    /// Session ID — "sessionId" field in the JSON.
    session_id: Option<String>,
    /// Macro state of the job: "working" | "blocked" | "done" | "stopped" | "failed".
    state: Option<String>,
    /// Tempo, orthogonal to state: "active" | "idle" | "blocked".
    /// When state=working + tempo=blocked => waiting for permission.
    /// When state=blocked + tempo=blocked => waiting for user input.
    tempo: Option<String>,
    /// Progress detail (can be null right after startup).
    detail: Option<String>,
    /// Pending question or action: "approve Write: /path" (permission) or a free-form question (input).
    needs: Option<String>,
    /// Original user prompt — fallback for detail.
    intent: Option<String>,
    /// Short name generated by the supervisor ("name" field).
    name: Option<String>,
    /// Working directory for the session.
    cwd: Option<String>,
    /// Creation timestamp — RFC3339/ISO 8601.
    created_at: Option<String>,
    /// Last-updated timestamp — RFC3339/ISO 8601.
    updated_at: Option<String>,
    /// Subtasks the supervisor is running for this job. Observed shape:
    /// {"tasks": 0, "queued": 0, "kinds": []} — or null.
    in_flight: Option<InFlight>,
}

#[derive(Deserialize, Default)]
struct InFlight {
    tasks: Option<u32>,
    queued: Option<u32>,
}

fn jobs_dir() -> Option<PathBuf> {
    dirs::home_dir().map(|h| h.join(".claude").join("jobs"))
}

/// Maps empirical state.json values to the internal InstanceState.
///
/// Requires both `state` and `tempo` because the distinction between "waiting
/// for permission" and "waiting for user input" is NOT in `state` alone but in
/// the state+tempo combination:
///   - state=working + tempo=blocked → WaitingPermission (approve <Tool>)
///   - state=blocked + tempo=blocked → WaitingInput (user question)
fn map_state(raw_state: &str, raw_tempo: &str) -> InstanceState {
    let state = raw_state.to_lowercase().replace([' ', '-'], "_");
    let tempo = raw_tempo.to_lowercase().replace([' ', '-'], "_");

    match state.as_str() {
        // Active or waiting for a background shell task result.
        "working" | "running" | "in_progress" => {
            // If tempo=blocked, the agent is halted waiting for approval
            // of a tool use (Write, Bash, etc.). needs="approve ..." confirms this.
            if tempo == "blocked" {
                InstanceState::WaitingPermission
            } else {
                InstanceState::Working
            }
        }
        // The agent asked the user a question and is waiting for a response.
        // Observed: state=blocked + tempo=blocked + needs=<free-form question>.
        "blocked" | "needs_input" | "waiting_input" | "awaiting_input" => {
            InstanceState::WaitingInput
        }
        // "done" is the empirically observed value for a successful completion.
        "completed" | "done" => InstanceState::Completed,
        "idle" => InstanceState::Idle,
        "failed" | "error" => InstanceState::Error,
        // "stopped" = stopped by the user; shown in grey with no useful action.
        "stopped" => InstanceState::Unknown,
        _ => InstanceState::Unknown,
    }
}

/// Parses an RFC3339 timestamp (e.g. "2026-06-06T15:55:52.871Z") to epoch seconds.
/// Does not depend on chrono: manually parses the numeric fields from the string.
/// Returns None if the format is not recognizable.
fn parse_rfc3339(s: &str) -> Option<u64> {
    // Expected format: YYYY-MM-DDTHH:MM:SS[.mmm]Z
    // We only look at the part up to the Z or UTC offset; fractional seconds are ignored.
    let s = s.trim();
    // Must be at least "YYYY-MM-DDTHH:MM:SSZ" = 20 chars
    if s.len() < 20 {
        return None;
    }
    let year: u64 = s[0..4].parse().ok()?;
    let month: u64 = s[5..7].parse().ok()?;
    let day: u64 = s[8..10].parse().ok()?;
    let hour: u64 = s[11..13].parse().ok()?;
    let min: u64 = s[14..16].parse().ok()?;
    let sec: u64 = s[17..19].parse().ok()?;

    // Approximate conversion to epoch (no leap-second adjustment; sufficient for UI).
    // Days since 1970-01-01.
    if year < 1970 || month < 1 || month > 12 || day < 1 || day > 31 {
        return None;
    }
    let days_per_month = [0u64, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
    let leap = (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);
    let mut days: u64 = 0;
    for y in 1970..year {
        days += if (y % 4 == 0 && y % 100 != 0) || y % 400 == 0 { 366 } else { 365 };
    }
    for m in 1..month {
        let d = if m == 2 && leap { 29 } else { days_per_month[m as usize] };
        days += d;
    }
    days += day - 1;
    Some(days * 86400 + hour * 3600 + min * 60 + sec)
}

/// Reads all state.json files and builds the set of background instances.
fn scan() -> Vec<Instance> {
    let Some(dir) = jobs_dir() else {
        return Vec::new();
    };
    let mut out = Vec::new();
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return out;
    };
    for entry in entries.flatten() {
        let state_path = entry.path().join("state.json");
        let Ok(text) = std::fs::read_to_string(&state_path) else {
            continue;
        };
        let Ok(js) = serde_json::from_str::<JobState>(&text) else {
            continue;
        };

        // session_id: prefer sessionId from the JSON; fall back to the directory name.
        let id = js
            .session_id
            .or_else(|| entry.file_name().to_str().map(String::from))
            .unwrap_or_default();
        if id.is_empty() {
            continue;
        }

        let raw_state = js.state.unwrap_or_default();
        let raw_tempo = js.tempo.unwrap_or_default();
        let cwd = js.cwd.unwrap_or_default();

        // detail: if there is a pending action ("needs": question or "approve ..."),
        // that is the most useful thing to display; otherwise fall through to
        // "detail", then "intent" (original prompt), then "name" (supervisor-generated).
        let detail = js
            .needs
            .filter(|s| !s.is_empty())
            .or_else(|| js.detail.filter(|s| !s.is_empty()))
            .or_else(|| js.intent.filter(|s| !s.is_empty()))
            .or(js.name);

        // Timestamps: RFC3339 → epoch secs; fall back to file mtime.
        let file_ts = mtime(&state_path);
        let started_at = js
            .created_at
            .as_deref()
            .and_then(parse_rfc3339)
            .unwrap_or(file_ts);
        let last_event_at = js
            .updated_at
            .as_deref()
            .and_then(parse_rfc3339)
            .unwrap_or(file_ts);

        let state = map_state(&raw_state, &raw_tempo);

        // TTL filter: the supervisor never deletes the state.json of finished
        // jobs, so terminal jobs (done/stopped/failed) older than REMOVE_SECS
        // are skipped to keep the list from accumulating fossils. Recent
        // completions stay visible — that feedback is useful.
        if expired_terminal(state, last_event_at, now_secs()) {
            continue;
        }

        // Read context tokens directly: scan runs on its own thread and the job
        // count is small, so a synchronous file read here is fine.
        let context_tokens = transcript::transcript_path(&cwd, &id)
            .as_deref()
            .and_then(transcript::read_context_tokens);

        // Subtasks in flight: tasks + queued, shown only when > 0.
        let in_flight_tasks = js.in_flight.as_ref().map(|f| {
            f.tasks.unwrap_or(0) + f.queued.unwrap_or(0)
        });

        out.push(Instance {
            session_id: id,
            project: project_from_cwd(&cwd),
            cwd,
            state,
            detail,
            source: Source::Background,
            started_at,
            last_event_at,
            context_tokens,
            in_flight_tasks,
        });
    }
    out
}

fn now_secs() -> u64 {
    SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()
}

/// True if the job is in a terminal state and its last update is older than
/// the removal TTL. Pure logic — unit-testable.
fn expired_terminal(state: InstanceState, last_event_at: u64, now: u64) -> bool {
    state.is_terminal() && now.saturating_sub(last_event_at) > crate::state::REMOVE_SECS
}

fn mtime(p: &PathBuf) -> u64 {
    std::fs::metadata(p)
        .and_then(|m| m.modified())
        .ok()
        .and_then(|t| t.duration_since(UNIX_EPOCH).ok())
        .map(|d| d.as_secs())
        .unwrap_or_else(|| {
            SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()
        })
}

fn rescan_and_emit(store: &Arc<Store>, app: &AppHandle) {
    store.set_background_snapshot(scan());
    refresh::refresh(app, store);
}

/// Starts the watcher on its own thread (notify is synchronous). Performs an
/// initial scan and then re-scans (with a simple debounce) on any change.
pub fn start(store: Arc<Store>, app: AppHandle) {
    std::thread::spawn(move || {
        rescan_and_emit(&store, &app);

        let Some(dir) = jobs_dir() else { return };
        let _ = std::fs::create_dir_all(&dir);

        let (tx, rx) = channel();
        let mut watcher: RecommendedWatcher = match notify::recommended_watcher(tx) {
            Ok(w) => w,
            Err(e) => {
                eprintln!("[jobs] could not create watcher: {e}");
                return;
            }
        };
        if let Err(e) = watcher.watch(&dir, RecursiveMode::Recursive) {
            eprintln!("[jobs] could not watch {dir:?}: {e}");
            return;
        }

        // Debounce: collapse bursts of events into a single rescan.
        loop {
            match rx.recv() {
                Ok(_) => {
                    while rx.recv_timeout(Duration::from_millis(150)).is_ok() {}
                    rescan_and_emit(&store, &app);
                }
                Err(_) => break,
            }
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::REMOVE_SECS;

    #[test]
    fn expired_terminal_filters_old_finished_jobs() {
        let now = 100_000;
        let old = now - REMOVE_SECS - 1;
        assert!(expired_terminal(InstanceState::Completed, old, now));
        assert!(expired_terminal(InstanceState::Error, old, now));
        assert!(expired_terminal(InstanceState::Unknown, old, now));
    }

    #[test]
    fn expired_terminal_keeps_recent_and_active_jobs() {
        let now = 100_000;
        let recent = now - 60;
        let old = now - REMOVE_SECS - 1;
        // Recent terminal: visible (useful feedback).
        assert!(!expired_terminal(InstanceState::Completed, recent, now));
        // Old but active: never filtered, the supervisor still owns it.
        assert!(!expired_terminal(InstanceState::Working, old, now));
        assert!(!expired_terminal(InstanceState::WaitingInput, old, now));
    }
}
